server:
  port: 8882
spring:
  application:
    name: hello-spring-cloud-admin-feign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/
feign:
  hystrix:
    enabled: true
